-- EnlaceExpress - INSERTS Oracle
-- Parte 1: datos iniciales y tablas de negocio
-- Generado a partir del contenido proporcionado.

-- BLOQUE 1
INSERT ALL
    INTO ROLES (ID, NAME, IS_ACTIVE) VALUES (1, 'ADMIN', 'ACTIVE')
    INTO ROLES (ID, NAME, IS_ACTIVE) VALUES (2, 'CLIENTE_EMPRESA', 'ACTIVE')
    INTO ROLES (ID, NAME, IS_ACTIVE) VALUES (3, 'DESPACHO', 'ACTIVE')
    INTO ROLES (ID, NAME, IS_ACTIVE) VALUES (4, 'MENSAJERO', 'ACTIVE')
    INTO ROLES (ID, NAME, IS_ACTIVE) VALUES (5, 'FACTURACION', 'ACTIVE')
    INTO ROLES (ID, NAME, IS_ACTIVE) VALUES (6, 'OPERADOR', 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 2
INSERT ALL
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (1, 'admin', 'admin@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (2, 'cliente01', 'cliente01@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (3, 'cliente02', 'cliente02@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (4, 'despacho01', 'despacho01@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (5, 'despacho02', 'despacho02@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (6, 'mensajero01', 'mensajero01@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (7, 'mensajero02', 'mensajero02@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (8, 'facturacion01', 'facturacion01@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (9, 'operador01', 'operador01@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (10, 'operador02', 'operador02@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (11, 'usuario11', 'usuario11@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (12, 'usuario12', 'usuario12@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (13, 'usuario13', 'usuario13@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (14, 'usuario14', 'usuario14@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (15, 'usuario15', 'usuario15@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (16, 'usuario16', 'usuario16@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (17, 'usuario17', 'usuario17@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (18, 'usuario18', 'usuario18@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (19, 'usuario19', 'usuario19@enlaceexpress.com', 'Password123', 'ACTIVE')
    INTO USERS (ID, USERNAME, EMAIL, PASSWORD, IS_ACTIVE) VALUES (20, 'usuario20', 'usuario20@enlaceexpress.com', 'Password123', 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 3
INSERT ALL
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (1, 1, 1, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (2, 2, 2, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (3, 2, 3, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (4, 3, 4, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (5, 3, 5, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (6, 4, 6, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (7, 4, 7, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (8, 5, 8, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (9, 6, 9, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (10, 6, 10, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (11, 6, 11, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (12, 2, 12, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (13, 2, 13, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (14, 3, 14, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (15, 4, 15, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (16, 5, 16, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (17, 6, 17, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (18, 2, 18, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (19, 3, 19, 'ACTIVE')
    INTO ROLE_USERS (ID, ROLE_ID, USER_ID, IS_ACTIVE) VALUES (20, 4, 20, 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 4
INSERT ALL
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (1, '/api/auth/login', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (2, '/api/auth/register', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (3, '/api/users', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (4, '/api/users', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (5, '/api/empresas', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (6, '/api/empresas', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (7, '/api/envios', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (8, '/api/envios', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (9, '/api/envios/{id}', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (10, '/api/envios/{id}', 'PUT', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (11, '/api/tracking', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (12, '/api/tracking', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (13, '/api/facturas', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (14, '/api/facturas', 'POST', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (15, '/api/mensajeros', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (16, '/api/rutas', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (17, '/api/tarifas', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (18, '/api/reportes', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (19, '/api/auditoria', 'GET', 'ACTIVE')
    INTO RESOURCES (ID, PATH, METHOD, IS_ACTIVE) VALUES (20, '/api/admin', 'GET', 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 5
INSERT ALL
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (1, 1, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (2, 2, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (3, 3, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (4, 4, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (5, 5, 2, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (6, 6, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (7, 7, 2, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (8, 8, 2, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (9, 9, 2, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (10, 10, 3, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (11, 11, 4, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (12, 12, 4, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (13, 13, 5, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (14, 14, 5, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (15, 15, 4, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (16, 16, 3, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (17, 17, 3, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (18, 18, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (19, 19, 1, 'ACTIVE')
    INTO RESOURCE_ROLES (ID, RESOURCE_ID, ROLE_ID, IS_ACTIVE) VALUES (20, 20, 1, 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 6
INSERT ALL
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (1, '900100001-1', 'Comercial Caribe S.A.S.', 'Carlos Mendoza', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (2, '900100002-2', 'Distribuciones del Norte S.A.S.', 'Laura Gómez', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (3, '900100003-3', 'Comercial Guajira S.A.S.', 'Andrés Pérez', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (4, '900100004-4', 'Servicios Logísticos S.A.S.', 'María Rodríguez', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (5, '900100005-5', 'Inversiones Caribe S.A.S.', 'Jorge Díaz', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (6, '900100006-6', 'Comercial del Valle S.A.S.', 'Ana Martínez', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (7, '900100007-7', 'Transportes Regionales S.A.S.', 'Pedro López', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (8, '900100008-8', 'Tecnología del Caribe S.A.S.', 'Sofía Torres', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (9, '900100009-9', 'Comercial La Guajira S.A.S.', 'Daniel Castro', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (10, '900100010-0', 'Alimentos del Norte S.A.S.', 'Camila Rojas', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (11, '900100011-1', 'Soluciones Empresariales S.A.S.', 'Felipe Vargas', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (12, '900100012-2', 'Comercial Riohacha S.A.S.', 'Valentina Ruiz', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (13, '900100013-3', 'Servicios del Caribe S.A.S.', 'Miguel Herrera', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (14, '900100014-4', 'Distribuciones Guajira S.A.S.', 'Natalia Silva', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (15, '900100015-5', 'Comercial Atlántico S.A.S.', 'Ricardo Moreno', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (16, '900100016-6', 'Logística Nacional S.A.S.', 'Paola Jiménez', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (17, '900100017-7', 'Productos del Caribe S.A.S.', 'Sebastián Peña', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (18, '900100018-8', 'Comercial Santa Marta S.A.S.', 'Diana Acosta', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (19, '900100019-9', 'Servicios del Magdalena S.A.S.', 'Luis Navarro', 'ACTIVE')
    INTO EMPRESAS (ID, NIT, RAZON_SOCIAL, CONTACTO_PRINCIPAL, IS_ACTIVE) VALUES (20, '900100020-0', 'Empresa Caribeña S.A.S.', 'Gabriela Molina', 'INACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 7
INSERT ALL
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (1, 1, 'Carlos Mendoza', 'Contacto principal de Comercial Caribe', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (2, 2, 'Laura Gómez', 'Contacto principal de Distribuciones del Norte', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (3, 3, 'Andrés Pérez', 'Contacto principal de Comercial Guajira', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (4, 4, 'María Rodríguez', 'Contacto principal de Servicios Logísticos', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (5, 5, 'Jorge Díaz', 'Contacto principal de Inversiones Caribe', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (6, 6, 'Ana Martínez', 'Contacto principal de Comercial del Valle', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (7, 7, 'Pedro López', 'Contacto principal de Transportes Regionales', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (8, 8, 'Sofía Torres', 'Contacto principal de Tecnología del Caribe', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (9, 9, 'Daniel Castro', 'Contacto principal de Comercial La Guajira', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (10, 10, 'Camila Rojas', 'Contacto principal de Alimentos del Norte', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (11, 11, 'Felipe Vargas', 'Contacto principal de Soluciones Empresariales', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (12, 12, 'Valentina Ruiz', 'Contacto principal de Comercial Riohacha', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (13, 13, 'Miguel Herrera', 'Contacto principal de Servicios del Caribe', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (14, 14, 'Natalia Silva', 'Contacto principal de Distribuciones Guajira', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (15, 15, 'Ricardo Moreno', 'Contacto principal de Comercial Atlántico', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (16, 16, 'Paola Jiménez', 'Contacto principal de Logística Nacional', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (17, 17, 'Sebastián Peña', 'Contacto principal de Productos del Caribe', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (18, 18, 'Diana Acosta', 'Contacto principal de Comercial Santa Marta', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (19, 19, 'Luis Navarro', 'Contacto principal de Servicios del Magdalena', 'ACTIVE')
    INTO CONTACTOS (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (20, 20, 'Gabriela Molina', 'Contacto principal de Empresa Caribeña', 'INACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 8
INSERT ALL
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (1, 1, 'Bodega Principal', 'Carrera 7 #10-20 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (2, 1, 'Sucursal Norte', 'Calle 15 #8-30 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (3, 2, 'Bodega Principal', 'Carrera 10 #12-25 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (4, 2, 'Sucursal Centro', 'Calle 10 #5-15 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (5, 3, 'Bodega Principal', 'Carrera 6 #11-40 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (6, 3, 'Sucursal Norte', 'Calle 18 #7-22 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (7, 4, 'Oficina Principal', 'Carrera 9 #20-10 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (8, 4, 'Centro Logístico', 'Calle 25 #10-05 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (9, 5, 'Oficina Principal', 'Carrera 8 #14-30 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (10, 5, 'Bodega', 'Calle 16 #9-18 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (11, 6, 'Oficina Principal', 'Carrera 12 #13-50 Valledupar', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (12, 6, 'Bodega', 'Calle 20 #11-25 Valledupar', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (13, 7, 'Terminal', 'Carrera 4 #30-10 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (14, 7, 'Oficina', 'Calle 12 #6-40 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (15, 8, 'Oficina Principal', 'Carrera 11 #16-20 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (16, 8, 'Centro Técnico', 'Calle 22 #8-15 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (17, 9, 'Bodega Principal', 'Carrera 5 #18-30 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (18, 9, 'Sucursal Centro', 'Calle 9 #7-12 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (19, 10, 'Bodega Principal', 'Carrera 13 #17-22 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (20, 10, 'Sucursal', 'Calle 19 #6-25 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (21, 11, 'Oficina Principal', 'Carrera 8 #21-10 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (22, 11, 'Centro Operativo', 'Calle 24 #9-15 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (23, 12, 'Oficina Principal', 'Carrera 7 #22-18 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (24, 12, 'Sucursal', 'Calle 11 #10-20 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (25, 13, 'Oficina Principal', 'Carrera 10 #25-30 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (26, 13, 'Centro Operativo', 'Calle 27 #7-15 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (27, 14, 'Bodega Principal', 'Carrera 6 #28-20 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (28, 14, 'Sucursal', 'Calle 13 #5-18 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (29, 15, 'Oficina Principal', 'Carrera 9 #30-22 Barranquilla', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (30, 15, 'Bodega', 'Calle 35 #12-10 Barranquilla', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (31, 16, 'Oficina Principal', 'Carrera 14 #18-40 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (32, 16, 'Centro Logístico', 'Calle 21 #10-15 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (33, 17, 'Bodega Principal', 'Carrera 5 #32-18 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (34, 17, 'Sucursal', 'Calle 17 #8-20 Riohacha', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (35, 18, 'Oficina Principal', 'Carrera 3 #12-10 Santa Marta', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (36, 18, 'Bodega', 'Calle 20 #5-25 Santa Marta', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (37, 19, 'Oficina Principal', 'Carrera 4 #15-20 Santa Marta', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (38, 19, 'Sucursal', 'Calle 22 #7-18 Santa Marta', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (39, 20, 'Oficina Principal', 'Carrera 2 #10-15 Cartagena', 'ACTIVE')
    INTO DIRECCIONES (ID, EMPRESA_ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (40, 20, 'Bodega', 'Calle 16 #4-22 Cartagena', 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 9
INSERT ALL
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (1, 'Carlos Rincón', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (2, 'Juan Pérez', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (3, 'Miguel Torres', 'Mensajero regional', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (4, 'Andrés Gómez', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (5, 'Luis Rodríguez', 'Mensajero regional', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (6, 'David Martínez', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (7, 'Jorge Díaz', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (8, 'Felipe López', 'Mensajero regional', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (9, 'Sebastián Castro', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (10, 'Ricardo Herrera', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (11, 'Daniel Moreno', 'Mensajero regional', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (12, 'Mateo Vargas', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (13, 'Nicolás Ruiz', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (14, 'Alejandro Silva', 'Mensajero regional', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (15, 'Kevin Jiménez', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (16, 'Samuel Acosta', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (17, 'Diego Navarro', 'Mensajero regional', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (18, 'Oscar Molina', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (19, 'Cristian Peña', 'Mensajero urbano', 'ACTIVE')
    INTO MENSAJEROS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (20, 'Fernando Acosta', 'Mensajero inactivo', 'INACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 10
INSERT ALL
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (1, 'Ruta Centro', 'Zona centro de Riohacha', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (2, 'Ruta Norte', 'Zona norte de Riohacha', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (3, 'Ruta Sur', 'Zona sur de Riohacha', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (4, 'Ruta Comercial', 'Zona comercial', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (5, 'Ruta Industrial', 'Zona industrial', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (6, 'Ruta Guajira', 'Municipios de La Guajira', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (7, 'Ruta Valledupar', 'Trayecto hacia Valledupar', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (8, 'Ruta Barranquilla', 'Trayecto hacia Barranquilla', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (9, 'Ruta Santa Marta', 'Trayecto hacia Santa Marta', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (10, 'Ruta Regional 1', 'Ruta regional norte', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (11, 'Ruta Regional 2', 'Ruta regional sur', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (12, 'Ruta Especial', 'Ruta para envíos especiales', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (13, 'Ruta Empresarial', 'Ruta para empresas', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (14, 'Ruta Express', 'Ruta de entregas rápidas', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (15, 'Ruta Metropolitana', 'Ruta metropolitana', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (16, 'Ruta Costera', 'Ruta por la zona costera', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (17, 'Ruta Occidente', 'Ruta occidental', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (18, 'Ruta Oriente', 'Ruta oriental', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (19, 'Ruta Nacional', 'Ruta nacional', 'ACTIVE')
    INTO RUTAS (ID, NOMBRE, DESCRIPCION, IS_ACTIVE) VALUES (20, 'Ruta Temporal', 'Ruta temporal', 'INACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 11
INSERT ALL
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (1, 'Tarifa Básica', 'Por paquete', 10000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (2, 'Tarifa Estándar', 'Por paquete', 15000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (3, 'Tarifa Express', 'Por prioridad', 20000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (4, 'Tarifa Regional', 'Por distancia', 25000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (5, 'Tarifa Premium', 'Por servicio', 30000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (6, 'Tarifa Empresarial', 'Por contrato', 18000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (7, 'Tarifa Comercial', 'Por paquete', 12000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (8, 'Tarifa Norte', 'Por distancia', 22000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (9, 'Tarifa Sur', 'Por distancia', 21000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (10, 'Tarifa Centro', 'Por zona', 11000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (11, 'Tarifa Guajira', 'Por distancia', 27000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (12, 'Tarifa Valledupar', 'Por distancia', 28000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (13, 'Tarifa Barranquilla', 'Por distancia', 32000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (14, 'Tarifa Santa Marta', 'Por distancia', 30000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (15, 'Tarifa Urgente', 'Por prioridad', 35000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (16, 'Tarifa Nocturna', 'Por horario', 26000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (17, 'Tarifa Corporativa', 'Por contrato', 24000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (18, 'Tarifa Especial', 'Por servicio', 40000, DATE '2026-01-01', NULL, 'ACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (19, 'Tarifa Antigua', 'Por paquete', 9000, DATE '2025-01-01', DATE '2025-12-31', 'INACTIVE')
    INTO TARIFAS (ID, NOMBRE, REGLA_CALCULO, VALOR_BASE, VIGENCIA_DESDE, VIGENCIA_HASTA, IS_ACTIVE) VALUES (20, 'Tarifa Temporal', 'Por servicio', 45000, DATE '2025-01-01', DATE '2025-12-31', 'INACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 12
INSERT ALL
    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (1, 1, 1, 1, 1, 1, 2, 'EX-2026-001', 'Documentos empresariales', 'ENTREGADO', 'NORMAL', TIMESTAMP '2026-08-01 08:00:00', TIMESTAMP '2026-08-02 14:00:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (2, 1, 2, 2, 2, 1, 2, 'EX-2026-002', 'Paquete comercial', 'ENTREGADO', 'ALTA', TIMESTAMP '2026-08-02 09:00:00', TIMESTAMP '2026-08-03 16:00:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (3, 2, 3, 3, 3, 3, 4, 'EX-2026-003', 'Documentos administrativos', 'EN_TRANSITO', 'NORMAL', TIMESTAMP '2026-08-03 10:00:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (4, 2, 4, 4, 4, 3, 4, 'EX-2026-004', 'Mercancía general', 'EN_ENTREGA', 'ALTA', TIMESTAMP '2026-08-04 11:00:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (5, 3, 5, 5, 5, 5, 6, 'EX-2026-005', 'Paquete tecnológico', 'ASIGNADO', 'NORMAL', TIMESTAMP '2026-08-05 08:30:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (6, 4, 6, 6, 6, 7, 8, 'EX-2026-006', 'Material logístico', 'EN_RECOGIDA', 'ALTA', TIMESTAMP '2026-08-06 09:15:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (7, 5, 7, 7, 7, 9, 10, 'EX-2026-007', 'Documentos legales', 'ENTREGADO', 'NORMAL', TIMESTAMP '2026-08-07 08:00:00', TIMESTAMP '2026-08-08 13:00:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (8, 6, 8, 8, 8, 11, 12, 'EX-2026-008', 'Productos comerciales', 'EN_TRANSITO', 'URGENTE', TIMESTAMP '2026-08-08 10:30:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (9, 7, 9, 9, 9, 13, 14, 'EX-2026-009', 'Repuestos', 'ENTREGADO', 'ALTA', TIMESTAMP '2026-08-09 09:00:00', TIMESTAMP '2026-08-10 15:00:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (10, 8, 10, 10, 10, 15, 16, 'EX-2026-010', 'Equipos electrónicos', 'CANCELADO', 'BAJA', TIMESTAMP '2026-08-10 12:00:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (11, 9, 11, 11, 11, 17, 18, 'EX-2026-011', 'Documentos comerciales', 'ENTREGADO', 'NORMAL', TIMESTAMP '2026-08-11 08:45:00', TIMESTAMP '2026-08-12 12:30:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (12, 10, 12, 12, 12, 19, 20, 'EX-2026-012', 'Productos alimenticios', 'CON_NOVEDAD', 'ALTA', TIMESTAMP '2026-08-12 09:20:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (13, 11, 13, 13, 13, 21, 22, 'EX-2026-013', 'Documentación empresarial', 'ENTREGADO', 'NORMAL', TIMESTAMP '2026-08-13 08:00:00', TIMESTAMP '2026-08-14 11:00:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (14, 12, 14, 14, 14, 23, 24, 'EX-2026-014', 'Paquete urgente', 'EN_ENTREGA', 'URGENTE', TIMESTAMP '2026-08-14 10:00:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (15, 13, 15, 15, 15, 25, 26, 'EX-2026-015', 'Insumos empresariales', 'ASIGNADO', 'NORMAL', TIMESTAMP '2026-08-15 08:10:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (16, 14, 16, 16, 16, 27, 28, 'EX-2026-016', 'Mercancía regional', 'EN_TRANSITO', 'ALTA', TIMESTAMP '2026-08-16 09:30:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (17, 15, 17, 17, 17, 29, 30, 'EX-2026-017', 'Documentos financieros', 'ENTREGADO', 'NORMAL', TIMESTAMP '2026-08-17 07:50:00', TIMESTAMP '2026-08-18 14:20:00', 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (18, 16, 18, 18, 18, 31, 32, 'EX-2026-018', 'Paquete corporativo', 'CREADO', 'BAJA', TIMESTAMP '2026-08-18 10:00:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (19, 17, 19, 19, 19, 33, 34, 'EX-2026-019', 'Productos comerciales', 'EN_TRANSITO', 'ALTA', TIMESTAMP '2026-08-19 11:00:00', NULL, 'ACTIVE')

    INTO ENVIOS (ID, EMPRESA_ID, MENSAJERO_ID, RUTA_ID, TARIFA_ID, DIRECCION_RECOGIDA_ID, DIRECCION_ENTREGA_ID, REFERENCIA, DESCRIPCION, ESTADO, PRIORIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, IS_ACTIVE)
    VALUES (20, 1, 2, 4, 1, 1, 2, 'EX-2026-020', 'Envío urgente empresarial', 'ENTREGADO', 'URGENTE', TIMESTAMP '2026-08-20 08:00:00', TIMESTAMP '2026-08-21 10:30:00', 'ACTIVE')
SELECT 1 FROM DUAL;

-- BLOQUE 13
INSERT ALL
    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (1, 1, 'PK-2026-001', 'Documentos', 1.2, 30, 20, 5, 'Documentos', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (2, 2, 'PK-2026-002', 'Paquete comercial', 4.5, 40, 30, 20, 'Mercancía', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (3, 3, 'PK-2026-003', 'Documentos administrativos', 2.0, 30, 25, 10, 'Documentos', 'EN_TRANSITO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (4, 4, 'PK-2026-004', 'Mercancía general', 8.5, 50, 40, 30, 'Mercancía', 'EN_TRANSITO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (5, 5, 'PK-2026-005', 'Equipo tecnológico', 6.0, 45, 35, 25, 'Tecnología', 'REGISTRADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (6, 6, 'PK-2026-006', 'Material logístico', 10.5, 60, 40, 35, 'Material', 'REGISTRADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (7, 7, 'PK-2026-007', 'Documentos legales', 1.5, 30, 20, 5, 'Documentos', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (8, 8, 'PK-2026-008', 'Productos comerciales', 7.2, 50, 40, 30, 'Mercancía', 'EN_TRANSITO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (9, 9, 'PK-2026-009', 'Repuestos', 12.0, 70, 45, 35, 'Repuestos', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (10, 10, 'PK-2026-010', 'Equipo electrónico', 5.5, 40, 35, 20, 'Tecnología', 'DEVUELTO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (11, 11, 'PK-2026-011', 'Documentos comerciales', 1.8, 30, 20, 5, 'Documentos', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (12, 12, 'PK-2026-012', 'Productos alimenticios', 15.0, 60, 45, 40, 'Alimentos', 'CON_NOVEDAD', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (13, 13, 'PK-2026-013', 'Documentación empresarial', 2.2, 35, 25, 8, 'Documentos', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (14, 14, 'PK-2026-014', 'Paquete urgente', 3.8, 40, 30, 20, 'Mercancía', 'EN_TRANSITO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (15, 15, 'PK-2026-015', 'Insumos empresariales', 9.0, 55, 40, 30, 'Insumos', 'REGISTRADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (16, 16, 'PK-2026-016', 'Mercancía regional', 13.5, 65, 45, 40, 'Mercancía', 'EN_TRANSITO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (17, 17, 'PK-2026-017', 'Documentos financieros', 1.4, 30, 20, 5, 'Documentos', 'ENTREGADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (18, 18, 'PK-2026-018', 'Paquete corporativo', 5.0, 45, 35, 25, 'Mercancía', 'REGISTRADO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (19, 19, 'PK-2026-019', 'Productos comerciales', 11.0, 60, 40, 35, 'Mercancía', 'EN_TRANSITO', 'ACTIVE')

    INTO PAQUETES
        (ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE)
    VALUES
        (20, 20, 'PK-2026-020', 'Envío urgente empresarial', 3.2, 35, 25, 15, 'Documentos', 'ENTREGADO', 'ACTIVE')

SELECT 1 FROM DUAL;

-- BLOQUE 14
SELECT ID, ENVIO_ID, CODIGO, DESCRIPCION, PESO, LARGO, ANCHO, ALTO, TIPO_CONTENIDO, ESTADO, IS_ACTIVE
FROM PAQUETES;
-- BLOQUE 15: EVENTOS_TRACKING
INSERT ALL
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (1, 1, 1, 'ENTREGADO', 'Entrega realizada correctamente', 11.5444, -72.9072, TIMESTAMP '2026-08-02 14:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (2, 2, 2, 'ENTREGADO', 'Paquete entregado al receptor', 11.5450, -72.9080, TIMESTAMP '2026-08-03 16:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (3, 3, 3, 'EN_TRANSITO', 'Envío en tránsito', 11.5500, -72.9000, TIMESTAMP '2026-08-04 12:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (4, 4, 4, 'EN_ENTREGA', 'Mensajero en ruta de entrega', 11.5520, -72.9050, TIMESTAMP '2026-08-05 13:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (5, 5, 5, 'ASIGNADO', 'Envío asignado al mensajero', 11.5600, -72.9100, TIMESTAMP '2026-08-05 15:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (6, 6, 6, 'EN_RECOGIDA', 'Mensajero en punto de recogida', 11.5650, -72.9150, TIMESTAMP '2026-08-06 10:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (7, 7, 7, 'ENTREGADO', 'Entrega confirmada', 11.5700, -72.9200, TIMESTAMP '2026-08-08 13:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (8, 8, 8, 'EN_TRANSITO', 'Paquete trasladándose a destino', 11.5750, -72.9250, TIMESTAMP '2026-08-09 11:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (9, 9, 9, 'ENTREGADO', 'Entrega confirmada', 11.5800, -72.9300, TIMESTAMP '2026-08-10 15:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (10, 10, 10, 'CANCELADO', 'Envío cancelado por solicitud', 11.5850, -72.9350, TIMESTAMP '2026-08-10 16:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (11, 11, 11, 'ENTREGADO', 'Entrega confirmada', 11.5900, -72.9400, TIMESTAMP '2026-08-12 12:30:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (12, 12, 12, 'CON_NOVEDAD', 'Novedad reportada durante entrega', 11.5950, -72.9450, TIMESTAMP '2026-08-13 13:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (13, 13, 13, 'ENTREGADO', 'Entrega confirmada', 11.6000, -72.9500, TIMESTAMP '2026-08-14 11:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (14, 14, 14, 'EN_ENTREGA', 'Envío en proceso de entrega', 11.6050, -72.9550, TIMESTAMP '2026-08-15 11:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (15, 15, 15, 'ASIGNADO', 'Envío asignado', 11.6100, -72.9600, TIMESTAMP '2026-08-15 14:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (16, 16, 16, 'EN_TRANSITO', 'Envío en tránsito', 11.6150, -72.9650, TIMESTAMP '2026-08-17 12:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (17, 17, 17, 'ENTREGADO', 'Entrega confirmada', 11.6200, -72.9700, TIMESTAMP '2026-08-18 14:20:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (18, 18, 18, 'CREADO', 'Envío creado', 11.6250, -72.9750, TIMESTAMP '2026-08-18 10:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (19, 19, 19, 'EN_TRANSITO', 'Envío en tránsito', 11.6300, -72.9800, TIMESTAMP '2026-08-20 12:00:00', 'ACTIVE')
    INTO EVENTOS_TRACKING (ID, ENVIO_ID, MENSAJERO_ID, ESTADO, DESCRIPCION, LATITUD, LONGITUD, FECHA_EVENTO, IS_ACTIVE) VALUES (20, 20, 2, 'ENTREGADO', 'Entrega urgente realizada', 11.6350, -72.9850, TIMESTAMP '2026-08-21 10:30:00', 'ACTIVE')
SELECT 1 FROM DUAL;
COMMIT;

-- BLOQUE 16: FACTURAS
INSERT ALL
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (1, 1, 1, 'FAC-2026-001', 10000, 1900, 11900, 'PAGADA', TIMESTAMP '2026-08-01 09:00:00', TIMESTAMP '2026-08-31 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (2, 1, 2, 'FAC-2026-002', 15000, 2850, 17850, 'PAGADA', TIMESTAMP '2026-08-02 09:00:00', TIMESTAMP '2026-09-01 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (3, 2, 3, 'FAC-2026-003', 20000, 3800, 23800, 'EMITIDA', TIMESTAMP '2026-08-03 09:00:00', TIMESTAMP '2026-09-02 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (4, 2, 4, 'FAC-2026-004', 25000, 4750, 29750, 'PENDIENTE', TIMESTAMP '2026-08-04 09:00:00', TIMESTAMP '2026-09-03 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (5, 3, 5, 'FAC-2026-005', 30000, 5700, 35700, 'PAGADA', TIMESTAMP '2026-08-05 09:00:00', TIMESTAMP '2026-09-04 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (6, 4, 6, 'FAC-2026-006', 18000, 3420, 21420, 'EMITIDA', TIMESTAMP '2026-08-06 09:00:00', TIMESTAMP '2026-09-05 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (7, 5, 7, 'FAC-2026-007', 12000, 2280, 14280, 'PAGADA', TIMESTAMP '2026-08-07 09:00:00', TIMESTAMP '2026-09-06 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (8, 6, 8, 'FAC-2026-008', 22000, 4180, 26180, 'PENDIENTE', TIMESTAMP '2026-08-08 09:00:00', TIMESTAMP '2026-09-07 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (9, 7, 9, 'FAC-2026-009', 21000, 3990, 24990, 'PAGADA', TIMESTAMP '2026-08-09 09:00:00', TIMESTAMP '2026-09-08 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (10, 8, 10, 'FAC-2026-010', 11000, 2090, 13090, 'ANULADA', TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-09-09 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (11, 9, 11, 'FAC-2026-011', 27000, 5130, 32130, 'PAGADA', TIMESTAMP '2026-08-11 09:00:00', TIMESTAMP '2026-09-10 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (12, 10, 12, 'FAC-2026-012', 28000, 5320, 33320, 'VENCIDA', TIMESTAMP '2026-08-12 09:00:00', TIMESTAMP '2026-08-20 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (13, 11, 13, 'FAC-2026-013', 32000, 6080, 38080, 'PAGADA', TIMESTAMP '2026-08-13 09:00:00', TIMESTAMP '2026-09-12 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (14, 12, 14, 'FAC-2026-014', 30000, 5700, 35700, 'EMITIDA', TIMESTAMP '2026-08-14 09:00:00', TIMESTAMP '2026-09-13 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (15, 13, 15, 'FAC-2026-015', 35000, 6650, 41650, 'PENDIENTE', TIMESTAMP '2026-08-15 09:00:00', TIMESTAMP '2026-09-14 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (16, 14, 16, 'FAC-2026-016', 24000, 4560, 28560, 'PAGADA', TIMESTAMP '2026-08-16 09:00:00', TIMESTAMP '2026-09-15 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (17, 15, 17, 'FAC-2026-017', 26000, 4940, 30940, 'PAGADA', TIMESTAMP '2026-08-17 09:00:00', TIMESTAMP '2026-09-16 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (18, 16, 18, 'FAC-2026-018', 40000, 7600, 47600, 'PENDIENTE', TIMESTAMP '2026-08-18 09:00:00', TIMESTAMP '2026-09-17 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (19, 17, 19, 'FAC-2026-019', 45000, 8550, 53550, 'EMITIDA', TIMESTAMP '2026-08-19 09:00:00', TIMESTAMP '2026-09-18 23:59:59', 'ACTIVE')
    INTO FACTURAS (ID, EMPRESA_ID, ENVIO_ID, NUMERO_FACTURA, SUBTOTAL, IMPUESTO, TOTAL, ESTADO, FECHA_EMISION, FECHA_VENCIMIENTO, IS_ACTIVE) VALUES (20, 1, 20, 'FAC-2026-020', 35000, 6650, 41650, 'PAGADA', TIMESTAMP '2026-08-20 09:00:00', TIMESTAMP '2026-09-19 23:59:59', 'ACTIVE')
SELECT 1 FROM DUAL;
COMMIT;

-- BLOQUE 17: PRUEBAS_ENTREGA
INSERT ALL
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (1, 1, 'FIRMA', 'firma_001.jpg', 'Entrega recibida correctamente', 'Carlos Pérez', '100100001', TIMESTAMP '2026-08-02 14:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (2, 2, 'FOTO', 'foto_002.jpg', 'Paquete entregado', 'Laura Gómez', '100100002', TIMESTAMP '2026-08-03 16:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (3, 3, 'DOCUMENTO', 'doc_003.pdf', 'Documento recibido', 'Andrés Pérez', '100100003', TIMESTAMP '2026-08-04 12:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (4, 4, 'FIRMA', 'firma_004.jpg', 'Entrega pendiente de confirmación', 'María López', '100100004', TIMESTAMP '2026-08-05 13:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (5, 5, 'FOTO', 'foto_005.jpg', 'Paquete registrado', 'Jorge Díaz', '100100005', TIMESTAMP '2026-08-05 15:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (6, 6, 'DOCUMENTO', 'doc_006.pdf', 'Recogida registrada', 'Ana Martínez', '100100006', TIMESTAMP '2026-08-06 10:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (7, 7, 'FIRMA', 'firma_007.jpg', 'Entrega confirmada', 'Pedro López', '100100007', TIMESTAMP '2026-08-08 13:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (8, 8, 'FOTO', 'foto_008.jpg', 'Paquete en tránsito', 'Sofía Torres', '100100008', TIMESTAMP '2026-08-09 11:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (9, 9, 'FIRMA', 'firma_009.jpg', 'Entrega confirmada', 'Daniel Castro', '100100009', TIMESTAMP '2026-08-10 15:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (10, 10, 'OTRA', 'registro_010.txt', 'Envío cancelado', 'Camila Rojas', '100100010', TIMESTAMP '2026-08-10 16:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (11, 11, 'FIRMA', 'firma_011.jpg', 'Entrega confirmada', 'Felipe Vargas', '100100011', TIMESTAMP '2026-08-12 12:30:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (12, 12, 'FOTO', 'foto_012.jpg', 'Novedad reportada', 'Valentina Ruiz', '100100012', TIMESTAMP '2026-08-13 13:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (13, 13, 'FIRMA', 'firma_013.jpg', 'Entrega confirmada', 'Miguel Herrera', '100100013', TIMESTAMP '2026-08-14 11:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (14, 14, 'CODIGO', 'codigo_014.txt', 'Código de entrega registrado', 'Natalia Silva', '100100014', TIMESTAMP '2026-08-15 11:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (15, 15, 'FOTO', 'foto_015.jpg', 'Paquete preparado', 'Ricardo Moreno', '100100015', TIMESTAMP '2026-08-15 14:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (16, 16, 'DOCUMENTO', 'doc_016.pdf', 'Envío en tránsito', 'Paola Jiménez', '100100016', TIMESTAMP '2026-08-17 12:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (17, 17, 'FIRMA', 'firma_017.jpg', 'Entrega confirmada', 'Sebastián Peña', '100100017', TIMESTAMP '2026-08-18 14:20:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (18, 18, 'OTRA', 'registro_018.txt', 'Envío creado', 'Diana Acosta', '100100018', TIMESTAMP '2026-08-18 10:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (19, 19, 'FOTO', 'foto_019.jpg', 'Paquete en tránsito', 'Luis Navarro', '100100019', TIMESTAMP '2026-08-20 12:00:00', 'ACTIVE')
    INTO PRUEBAS_ENTREGA (ID, ENVIO_ID, TIPO_PRUEBA, REFERENCIA_ARCHIVO, OBSERVACION, NOMBRE_RECEPTOR, DOCUMENTO_RECEPTOR, FECHA_PRUEBA, IS_ACTIVE) VALUES (20, 20, 'CODIGO', 'codigo_020.txt', 'Entrega urgente confirmada', 'Carlos Pérez', '100100020', TIMESTAMP '2026-08-21 10:30:00', 'ACTIVE')
SELECT 1 FROM DUAL;
COMMIT;

-- BLOQUE 18: REFRESH_TOKENS
INSERT ALL
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (1, 1, 'TOKEN-001-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (2, 2, 'TOKEN-002-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (3, 3, 'TOKEN-003-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (4, 4, 'TOKEN-004-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (5, 5, 'TOKEN-005-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (6, 6, 'TOKEN-006-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (7, 7, 'TOKEN-007-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (8, 8, 'TOKEN-008-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (9, 9, 'TOKEN-009-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
    INTO REFRESH_TOKENS (ID, USER_ID, TOKEN, EXPIRES_AT, REVOKED_AT) VALUES (10, 10, 'TOKEN-010-ENLACE-EXPRESS', TIMESTAMP '2026-12-31 23:59:59', NULL)
SELECT 1 FROM DUAL;
COMMIT;

-- BLOQUE 19: AUDITORIA
INSERT ALL
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (1, 'USERS', 1, 'INSERT', 'Creación del usuario administrador', TIMESTAMP '2026-08-01 08:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (2, 'EMPRESAS', 1, 'INSERT', 'Registro de empresa Comercial Caribe', TIMESTAMP '2026-08-01 08:10:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (3, 'EMPRESAS', 2, 'INSERT', 'Registro de empresa Distribuciones del Norte', TIMESTAMP '2026-08-01 08:15:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (4, 'ENVIOS', 1, 'INSERT', 'Creación del envío EX-2026-001', TIMESTAMP '2026-08-01 09:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (5, 'ENVIOS', 2, 'INSERT', 'Creación del envío EX-2026-002', TIMESTAMP '2026-08-02 09:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (6, 'ENVIOS', 3, 'UPDATE', 'Actualización del estado del envío', TIMESTAMP '2026-08-04 12:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (7, 'ENVIOS', 4, 'UPDATE', 'Actualización del estado del envío', TIMESTAMP '2026-08-05 13:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (8, 'PAQUETES', 1, 'INSERT', 'Registro del paquete PK-2026-001', TIMESTAMP '2026-08-01 09:05:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (9, 'FACTURAS', 1, 'INSERT', 'Generación de factura FAC-2026-001', TIMESTAMP '2026-08-01 09:10:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (10, 'FACTURAS', 2, 'UPDATE', 'Factura marcada como pagada', TIMESTAMP '2026-08-03 17:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (11, 'EVENTOS_TRACKING', 1, 'INSERT', 'Registro de evento de entrega', TIMESTAMP '2026-08-02 14:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (12, 'PRUEBAS_ENTREGA', 1, 'INSERT', 'Registro de prueba de entrega', TIMESTAMP '2026-08-02 14:05:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (13, 'ENVIOS', 10, 'UPDATE', 'Envío cancelado', TIMESTAMP '2026-08-10 16:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (14, 'ENVIOS', 12, 'UPDATE', 'Novedad registrada en el envío', TIMESTAMP '2026-08-13 13:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (15, 'USERS', 6, 'UPDATE', 'Actualización del usuario mensajero', TIMESTAMP '2026-08-15 08:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (16, 'RUTAS', 20, 'UPDATE', 'Ruta marcada como inactiva', TIMESTAMP '2026-08-16 08:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (17, 'TARIFAS', 19, 'UPDATE', 'Tarifa antigua desactivada', TIMESTAMP '2026-08-17 08:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (18, 'PAQUETES', 10, 'UPDATE', 'Paquete marcado como devuelto', TIMESTAMP '2026-08-18 10:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (19, 'FACTURAS', 12, 'UPDATE', 'Factura marcada como vencida', TIMESTAMP '2026-08-20 09:00:00')
    INTO AUDITORIA (ID, TABLA_AFECTADA, REGISTRO_ID, ACCION, DESCRIPCION, FECHA_EVENTO) VALUES (20, 'ENVIOS', 20, 'UPDATE', 'Entrega urgente completada', TIMESTAMP '2026-08-21 10:30:00')
SELECT 1 FROM DUAL;
COMMIT;
